  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2025-07-25T00:01:52.627+0000] {scheduler_job_runner.py:989} INFO - Starting the scheduler
[2025-07-25T00:01:52.634+0000] {executor_loader.py:269} INFO - Loaded executor: :LocalExecutor:
[2025-07-25 00:01:52 +0000] [156581] [INFO] Starting gunicorn 23.0.0
[2025-07-25 00:01:52 +0000] [156581] [ERROR] Connection in use: ('::', 8793)
[2025-07-25 00:01:52 +0000] [156581] [ERROR] connection to ('::', 8793) failed: [Errno 98] Address already in use
[2025-07-25T00:01:52.673+0000] {scheduler_job_runner.py:2128} INFO - Adopting or resetting orphaned tasks for active dag runs
[2025-07-25 00:01:53 +0000] [156581] [ERROR] Connection in use: ('::', 8793)
[2025-07-25 00:01:53 +0000] [156581] [ERROR] connection to ('::', 8793) failed: [Errno 98] Address already in use
[2025-07-25 00:01:54 +0000] [156581] [ERROR] Connection in use: ('::', 8793)
[2025-07-25 00:01:54 +0000] [156581] [ERROR] connection to ('::', 8793) failed: [Errno 98] Address already in use
[2025-07-25 00:01:55 +0000] [156581] [ERROR] Connection in use: ('::', 8793)
[2025-07-25 00:01:55 +0000] [156581] [ERROR] connection to ('::', 8793) failed: [Errno 98] Address already in use
[2025-07-25 00:01:56 +0000] [156581] [ERROR] Connection in use: ('::', 8793)
[2025-07-25 00:01:56 +0000] [156581] [ERROR] connection to ('::', 8793) failed: [Errno 98] Address already in use
[2025-07-25 00:01:57 +0000] [156581] [ERROR] Can't connect to ('::', 8793)
[2025-07-25T00:06:52.838+0000] {scheduler_job_runner.py:2128} INFO - Adopting or resetting orphaned tasks for active dag runs
